import { Serialization } from "@flamework-experimental/core";
import { RunService } from "@rbxts/services";
import { createEvent, decodeArguments } from "../event/createEvent";
import { NetworkInfo } from "../types";
import { NetworkingFunctionError } from "./errors";
import { MiddlewareFactory } from "../middleware/types";
import { Skip, SkipBadRequest } from "../middleware/skip";
import { Guards, Processor, createProcessor, withoutPlayer } from "../middleware/processor";

export interface CreateFunctionReceiverOptions {
	/**
	 * The namespace this event should be created in.
	 */
	namespace: string;

	/**
	 * The name of the remote instance, not necessarily unique and used for debugging purposes.
	 */
	debugName: string;

	/**
	 * The remote's ID which must be unique.
	 */
	id: string;

	/**
	 * Information about the network, which includes some of the above.
	 *
	 * Passed to the middleware.
	 */
	networkInfo: NetworkInfo;

	/**
	 * The middleware a request goes through before it reaches the callback.
	 */
	incomingMiddleware?: MiddlewareFactory<any[], any>[];

	/**
	 * The generated argument checks, run on a request before any middleware. A request that fails
	 * them is rejected with `BadRequest`.
	 */
	incomingGuards?: Guards;

	/**
	 * Unpacks the request's argument list. Absent when the project does not enable serialization.
	 */
	argsDecoder?: Serialization.Decoder;

	/**
	 * Called when a request cannot be decoded; the caller receives `BadRequest`.
	 */
	onMalformed?: (player: Player | undefined, message: string) => void;
}

export interface RequestInfo {
	nextId: number;
	requests: Map<number, (value: unknown, rejection?: NetworkingFunctionError) => void>;
}

export interface FunctionReceiverInterface {
	/** `pack`: turns a successful result into `[payload, blobs?]`, generated by the transformer. */
	setServerCallback(
		callback: (player: Player, ...args: unknown[]) => unknown,
		pack?: (value: unknown) => unknown,
	): void;
	setClientCallback(callback: (...args: unknown[]) => unknown, pack?: (value: unknown) => unknown): void;
	invoke(player: Player | undefined, ...args: unknown[]): Promise<unknown>;
}

export function createFunctionReceiver(options: CreateFunctionReceiverOptions): FunctionReceiverInterface {
	const event = createEvent({
		namespace: options.namespace,
		debugName: options.debugName,
		id: options.id,
		networkInfo: options.networkInfo,
	});

	// Which half this function is, fixed when it is made: the server's callback is given the sender.
	const isServer = RunService.IsServer();

	// Guards, then middleware, then the callback: plain calls in the thread handling the request, a
	// Promise any of them returns waited for in place and a cancelled one read as `Networking.Skip`.
	let process: Processor | undefined;
	let packResult: ((value: unknown) => unknown) | undefined;

	const setCallback = (
		newCallback: (...args: never[]) => unknown,
		pack: ((value: unknown) => unknown) | undefined,
	) => {
		packResult = pack;
		process = createProcessor(
			options.incomingMiddleware,
			options.networkInfo,
			isServer ? (newCallback as Processor) : withoutPlayer(newCallback),
			options.incomingGuards,
			SkipBadRequest,
			Skip,
		);
	};

	/**
	 * With serialization, a successful value leaves packed as `[payload, blobs?]`, or nothing at all
	 * when the result type carries nothing (`void`); errors always go back as they are. It is packed
	 * here, after the middleware, so a value a middleware returns is packed like the callback's own.
	 * A blob list that came out empty is left off, as a request's is (see `functions/`).
	 */
	const respond = (player: Player | undefined, id: unknown, processResult: unknown, value?: unknown) => {
		if (processResult === true && packResult) {
			const packed = packResult(value) as [buffer, Array<defined> | undefined] | undefined;
			if (packed === undefined) {
				event.fireEither(player, id, processResult);
				return;
			}

			const blobs = packed[1];
			if (blobs === undefined || next(blobs)[0] === undefined) {
				event.fireEither(player, id, processResult, packed[0]);
			} else {
				event.fireEither(player, id, processResult, packed[0], blobs);
			}
		} else {
			event.fireEither(player, id, processResult, value);
		}
	};

	/** A request that raised -- in a guard, a middleware, the callback, its Promise or the packing -- is answered `false`. */
	const fail = (player: Player | undefined, id: unknown, reason: unknown) => {
		warn(`Failed to process request to '${options.debugName}'`);
		warn(reason);

		event.fireEither(player, id, false);
	};

	// Runs on the thread the event's signal gives this handler, one per request.
	const processRequest = (player: Player | undefined, id: unknown, ...args: unknown[]) => {
		const current = process;
		if (!current) {
			return event.fireEither(player, id, NetworkingFunctionError.Unprocessed);
		}

		const decoded = decodeArguments(options.argsDecoder, player, args, options.onMalformed);
		if (!decoded) {
			return event.fireEither(player, id, NetworkingFunctionError.BadRequest);
		}

		const [ok, value] = pcall(current, player, ...decoded);
		if (!ok) {
			return fail(player, id, value);
		}

		const [sent, reason] = pcall(respond, player, id, getProcessResult(value), value);
		if (!sent) {
			fail(player, id, reason);
		}
	};

	if (isServer) {
		event.connectServer(processRequest);
	} else {
		event.connectClient((id, ...args) => processRequest(undefined, id, ...args));
	}

	return {
		setServerCallback(callback, pack) {
			setCallback(callback, pack);
		},

		setClientCallback(callback, pack) {
			setCallback(callback, pack);
		},

		invoke(player, ...args) {
			const current = process;
			if (!current) {
				return Promise.reject(NetworkingFunctionError.Unprocessed);
			}

			// The Promise `predict` returns is the only one: the chain runs in its executor's thread.
			return new Promise<unknown>((resolve, reject) => {
				const value = current(player, ...args);
				const processResult = getProcessResult(value);
				if (processResult !== true) {
					reject(processResult);
				} else {
					resolve(value);
				}
			});
		},
	};
}

function getProcessResult(value: unknown) {
	return value === Skip
		? NetworkingFunctionError.Cancelled
		: value === SkipBadRequest
			? NetworkingFunctionError.BadRequest
			: true;
}
