import { Serialization } from "@flamework-experimental/core";
import { RunService } from "@rbxts/services";
import { createEvent, decodeArguments } from "../event/createEvent";
import { NetworkInfo } from "../types";
import { NetworkingFunctionError } from "./errors";
import { createMiddlewareProcessor } from "../middleware/createMiddlewareProcessor";
import { MiddlewareFactory, MiddlewareProcessor } from "../middleware/types";
import { Skip, SkipBadRequest } from "../middleware/skip";

export interface CreateFunctionReceiverOptions {
	/**
	 * The namespace this event should be created in.
	 */
	namespace: string;

	/**
	 * The name of the remote instance, not necessarily unique and used for debugging purposes.
	 */
	debugName: string;

	/**
	 * The remote's ID which must be unique.
	 */
	id: string;

	/**
	 * Information about the network, which includes some of the above.
	 *
	 * Passed to the middleware.
	 */
	networkInfo: NetworkInfo;

	/**
	 * This function will be called when we receive a response, and can be used to resolve or reject values.
	 */
	incomingMiddleware?: MiddlewareFactory<any[], any>[];

	/**
	 * Unpacks the request's argument list. Absent when the project does not enable serialization.
	 */
	argsDecoder?: Serialization.Decoder;

	/**
	 * Called when a request cannot be decoded; the caller receives `BadRequest`.
	 */
	onMalformed?: (player: Player | undefined, message: string) => void;
}

export interface RequestInfo {
	nextId: number;
	requests: Map<number, (value: unknown, rejection?: NetworkingFunctionError) => void>;
}

export interface FunctionReceiverInterface {
	/** `pack`: turns a successful result into `[payload, blobs?]`, generated by the transformer. */
	setServerCallback(
		callback: (player: Player, ...args: unknown[]) => unknown,
		pack?: (value: unknown) => unknown,
	): void;
	setClientCallback(callback: (...args: unknown[]) => unknown, pack?: (value: unknown) => unknown): void;
	invoke(player: Player | undefined, ...args: unknown[]): Promise<unknown>;
}

export function createFunctionReceiver(options: CreateFunctionReceiverOptions): FunctionReceiverInterface {
	const event = createEvent({
		namespace: options.namespace,
		debugName: options.debugName,
		id: options.id,
		networkInfo: options.networkInfo,
	});

	let callback: MiddlewareProcessor<unknown[], unknown>;
	let packResult: ((value: unknown) => unknown) | undefined;

	const setCallback = (
		newCallback: (...args: never[]) => unknown,
		pack: ((value: unknown) => unknown) | undefined,
	) => {
		packResult = pack;
		callback = createMiddlewareProcessor(options.incomingMiddleware, options.networkInfo, (player, ...args) => {
			if (RunService.IsServer()) {
				return newCallback(player as never, ...(args as never[]));
			} else {
				return newCallback(...(args as never[]));
			}
		});
	};

	/**
	 * With serialization, a successful value leaves packed as `[payload, blobs?]`, or nothing at all
	 * when the result type carries nothing (`void`); errors always go back as they are. It is packed
	 * here, after the middleware, so a value a middleware returns is packed like the callback's own.
	 */
	const respond = (player: Player | undefined, id: unknown, processResult: unknown, value?: unknown) => {
		if (processResult === true && packResult) {
			const packed = packResult(value) as [buffer, Array<defined> | undefined] | undefined;
			if (packed !== undefined) {
				event.fireEither(player, id, processResult, packed[0], packed[1]);
			} else {
				event.fireEither(player, id, processResult);
			}
		} else {
			event.fireEither(player, id, processResult, value);
		}
	};

	const processRequest = (player: Player | undefined, id: unknown, ...args: unknown[]) => {
		if (!callback) {
			return event.fireEither(player, id, NetworkingFunctionError.Unprocessed);
		}

		const decoded = decodeArguments(options.argsDecoder, player, args, options.onMalformed);
		if (!decoded) {
			return event.fireEither(player, id, NetworkingFunctionError.BadRequest);
		}

		const processing = callback(player, ...decoded)
			.then((value) => respond(player, id, getProcessResult(value), value))
			.catch((reason) => {
				warn(`Failed to process request to '${options.debugName}'`);
				warn(reason);

				event.fireEither(player, id, false);
			});

		// A callback or middleware can return a promise that is then cancelled, and cancellation
		// reaches this chain, where neither handler above runs: the request would go unanswered.
		processing.finally(() => {
			if (processing.getStatus() === Promise.Status.Cancelled) {
				event.fireEither(player, id, NetworkingFunctionError.Cancelled);
			}
		});
	};

	if (RunService.IsServer()) {
		event.connectServer((player, id, ...args) => processRequest(player, id, ...args));
	} else {
		event.connectClient((id, ...args) => processRequest(undefined, id, ...args));
	}

	return {
		setServerCallback(callback, pack) {
			setCallback(callback, pack);
		},

		setClientCallback(callback, pack) {
			setCallback(callback, pack);
		},

		invoke(player, ...args) {
			if (!callback) {
				return Promise.reject(NetworkingFunctionError.Unprocessed);
			}

			return callback(player, ...args).then((value) => {
				const processResult = getProcessResult(value);
				if (processResult !== true) return Promise.reject(processResult);

				return value;
			});
		},
	};
}

function getProcessResult(value: unknown) {
	return value === Skip
		? NetworkingFunctionError.Cancelled
		: value === SkipBadRequest
			? NetworkingFunctionError.BadRequest
			: true;
}
