import { Reflect } from "@flamework/core";
import type { t } from "@rbxts/t";

/**
 * This enum dictates how component instance guards interact with StreamingEnabled.
 */
export enum ComponentStreamingMode {
	/**
	 * This disables instance guard streaming, and will only run the instance guard once.
	 */
	Disabled,

	/**
	 * This will watch for any changes to the instance tree, and rerun the instance guards.
	 */
	Watching,

	/**
	 * This determines the appropriate streaming mode based on a couple of factors.
	 *
	 * If on the server, this will always behave like `Disabled`.
	 *
	 * If on the client, and the attached instance is an `Atomic` model, this will behave like `Disabled`.
	 *
	 * Otherwise, this behaves like `Watching`.
	 */
	Contextual,

	/**
	 * This is equivalent to {@link ComponentStreamingMode.Contextual Contextual}.
	 */
	Default = Contextual,
}

/**
 * A link between a component and an instance named by one of its attributes or by its instance
 * tree. Written by the transformer from the component's type parameters; there is no reason to
 * write one by hand.
 */
export interface ComponentLink {
	/**
	 * `attribute` reads an `InstanceHandle` attribute, `child` looks the instance up by name in the
	 * component's own tree.
	 */
	kind: "attribute" | "child";

	/**
	 * The name of the attribute or of the child.
	 */
	name: string;

	/**
	 * Whether a missing instance is allowed, which it is when the declared type includes
	 * `undefined`.
	 */
	optional: boolean;

	/**
	 * Guard for the linked instance. Attribute links only: a child is already covered by the
	 * component's own instance guard.
	 */
	guard?: t.check<unknown>;

	/**
	 * The identifier of the component that has to exist on the linked instance, when the declared
	 * type is a component rather than an Instance.
	 */
	component?: string;
}

export interface ComponentConfig {
	/**
	 * The CollectionService tag this component is associated with.
	 */
	tag?: string;

	/**
	 * Override guards for specified attributes.
	 */
	attributes?: { [key: string]: t.check<unknown> };

	/**
	 * By default, Flamework will not construct components which do not pass the specified attribute guards.
	 * You can specify default values which Flamework will use instead of cancelling the component's construction.
	 */
	defaults?: { [key: string]: unknown };

	/**
	 * Overrides the guard generated by Flamework to validate instance trees.
	 */
	instanceGuard?: t.check<unknown>;

	/**
	 * Should this instance be ignored?
	 *
	 * This property differs from `instanceGuard` because it cancels the CollectionService event,
	 * whereas `instanceGuard` may continue to fire, along with other checks.
	 */
	predicate?: (instance: Instance) => boolean;

	/**
	 * Should this component watch for changes to attributes?
	 *
	 * This will disable `onAttributeChanged` events in the component, as well.
	 */
	refreshAttributes?: boolean;

	/**
	 * Specifies where components can be constructed via CollectionService.
	 * This has higher priority than `ancestorBlacklist`, including the default blacklist.
	 *
	 * This has the same behavior as a predicate.
	 */
	ancestorWhitelist?: Instance[];

	/**
	 * Specifies where components can not be constructed via CollectionService.
	 * Defaults to ServerStorage and ReplicatedStorage.
	 *
	 * This has the same behavior as a predicate.
	 */
	ancestorBlacklist?: Instance[];

	/**
	 * Flamework will warn whenever a component isn't able to be created while watching for CollectionService tags,
	 * this allows you to adjust how long until that warning appears.
	 *
	 * Defaults to 5, set to 0 to disable.
	 */
	warningTimeout?: number;

	/**
	 * How long an instance-valued attribute may go unresolved before Flamework warns about it.
	 *
	 * An attribute holds an `InstanceHandle`, which resolves to nothing until the instance it
	 * points at has streamed in at least once. Defaults to `warningTimeout`, set to 0 to disable.
	 */
	attributeWarningTimeout?: number;

	/**
	 * The links generated from this component's type parameters.
	 *
	 * Written by the transformer, which reads them off `BaseComponent`'s type parameters; there is
	 * no reason to set this by hand.
	 */
	links?: ComponentLink[];

	/**
	 * Override the component streaming mode, defaults to `Contextual`.
	 */
	streamingMode?: ComponentStreamingMode;

	/**
	 * Registered only while at least one of these scopes is active in the build, on top of the
	 * module's and the registration's own conditions. An unregistered component is never attached
	 * to a tagged instance.
	 */
	activeIn?: readonly string[];

	/** Never registered while any of these scopes is active in the build. */
	inactiveIn?: readonly string[];
}

/**
 * Register a class as a Component.
 *
 * `flamework:parameters` is what `Components` reads to discover which of a component's constructor
 * dependencies are themselves components, so that its tracker can wait for them.
 *
 * @metadata reflect identifier flamework:implements flamework:dependencies flamework:parameters injectable
 * @metadata macro {@link opts intrinsic-const} {@link opts intrinsic-component-config}
 */
export function Component(opts?: ComponentConfig) {
	return (object: object) => {
		Reflect.defineMetadata(object, "flamework:component", true);
		Reflect.defineMetadata(object, "flamework:componentConfig", opts);
	};
}
