import ts from "typescript";
import fs from "fs";
import crypto from "crypto";
import path from "path";
import chalk from "chalk";
import Hashids from "hashids";
import { transformNode } from "../transformations/transformNode";
import { Cache } from "../util/cache";
import { getPackageJson } from "../util/functions/getPackageJson";
import { BuildInfo } from "./buildInfo";
import { Logger } from "./logger";
import { f } from "../util/factory";
import { isPathDescendantOf } from "../util/functions/isPathDescendantOf";
import { getTsBuildInfoPath, isCleanBuildDirectory } from "../util/functions/isCleanBuildDirectory";
import { parseCommandLine } from "../util/functions/parseCommandLine";
import { createPathTranslator } from "../util/functions/createPathTranslator";
import { arePathsEqual } from "../util/functions/arePathsEqual";
import { NodeMetadata } from "./nodeMetadata";
import { RbxPath, RojoResolver } from "@roblox-ts/rojo-resolver";
import { assert } from "../util/functions/assert";
import { shuffle } from "../util/functions/shuffle";
import glob from "glob";
import type { PathTranslator } from "@roblox-ts/path-translator";
import { createPluginHost, type PluginHost } from "../transformations/plugins/pluginHost";
import { tryResolveTS } from "../util/functions/tryResolve";
import {
	addSchemaReference,
	fingerprintProjectConfig,
	getRuntimeConfig,
	loadProjectConfig,
	ProjectConfig,
	TransformerEntry,
} from "../util/projectConfig";
import type { Env } from "../util/env";
import { Diagnostics } from "./diagnostics";
import { FLAMEWORK_SCOPE, CORE_PACKAGE } from "../util/packages";
import { findPlaceSource, findSourcePath, type SourcePathState } from "../util/functions/findSourcePath";

/**
 * The transformer's options: the `transformer` section of `flamework.config.json`, the only place
 * they are read from. The tsconfig plugin entry takes none of them (see `TransformerEntry`).
 */
export interface TransformerConfig {
	/**
	 * Transformer plugins to load, which can register additional macro types.
	 *
	 * Each entry is either a module specifier (resolved from the project root) or a path relative
	 * to the project root, optionally paired with options passed to the plugin as `api.options`.
	 */
	plugins?: (string | { path: string; options?: Record<string, unknown> })[];

	/**
	 * Disables TypeScript's own semantic diagnostics.
	 * Improves performance, but results in increased risk of incorrect compilation as well as messed up diagnostic spans.
	 */
	noSemanticDiagnostics?: boolean;

	/**
	 * This is the salt used for hashes generated by Flamework.
	 * Defaults to a randomly generated 64 byte salt.
	 */
	salt?: string;

	/**
	 * A package's ids carry it, so that they cannot collide with another package's or a game's.
	 * Defaults to the package name in a package; a game has no prefix unless it sets one, and needs
	 * none, since none of its own ids starts with a package's `prefix:`.
	 */
	hashPrefix?: string;

	/**
	 * Whether to enable flamework's obfuscation.
	 *
	 * This comprises of:
	 * 1. random event names
	 * 2. shortened ids
	 */
	obfuscation?: boolean;

	/**
	 * Determines the id generation mode.
	 * Defaults to "obfuscated" with obfuscation on, else "full", and should only be configured in game projects.
	 */
	idGenerationMode?: "full" | "short" | "tiny" | "obfuscated";

	/**
	 * Some experimental optimizations
	 */
	optimizations?: {
		/**
		 * When set, object and union types that occur at least this many times inside one generated
		 * guard are emitted once as a local and referenced, instead of being inlined every time.
		 */
		guardGenerationDedupLimit?: number;
	};
}

/**
 * The tsbuildinfo, relative to the project and with forward slashes on every platform, as the
 * messages that ask for it to be deleted name it.
 */
export function buildInfoFileName(currentDirectory: string, options: ts.CompilerOptions) {
	const buildInfoFile = getTsBuildInfoPath(options);
	return buildInfoFile !== undefined
		? path.relative(currentDirectory, buildInfoFile).replace(/\\/g, "/")
		: "the tsbuildinfo";
}

export class TransformState {
	public parsedCommandLine = parseCommandLine();
	public currentDirectory = this.parsedCommandLine.project;
	public options = this.program.getCompilerOptions();
	public srcDir = this.options.rootDir ?? this.currentDirectory;
	public outDir = this.options.outDir ?? this.currentDirectory;
	public rootDirs = this.options.rootDirs ? this.options.rootDirs : [this.srcDir];
	public typeChecker = this.program.getTypeChecker();

	public rojoResolver?: RojoResolver;
	public pathTranslator!: PathTranslator;
	public buildInfo!: BuildInfo;

	public includeDirectory: string;
	public rootDirectory: string;
	public packageName: string;
	public isGame: boolean;
	public pluginHost?: PluginHost;

	public isUserMacroCache = new Map<ts.Symbol, boolean>();
	public nextRootStatements = new Array<ts.Statement>();
	public flameworkGuardLibraryPath?: string;

	/**
	 * Whether this process started from the previous build's `flamework.build` rather than a fresh
	 * one, which an incremental build does so that the files it does not recompile keep their ids.
	 * Under obfuscation that also keeps the ids a release was meant to rotate.
	 */
	private buildInfoReused = false;

	private setupBuildInfo() {
		let baseBuildInfo = BuildInfo.fromDirectory(this.currentDirectory);
		if (!baseBuildInfo || (Cache.isInitialCompile && isCleanBuildDirectory(this.options))) {
			const buildInfoFile = getTsBuildInfoPath(this.options);
			if (buildInfoFile !== undefined && ts.sys.fileExists(buildInfoFile)) {
				// Said and stopped as the version check stops, without a stack: nothing here is a bug.
				Logger.writeLine(
					chalk.red("Flamework cannot be built in a dirty environment."),
					`This incremental build has no flamework.build to match the files it does not recompile. Delete ${buildInfoFileName(this.currentDirectory, this.options)} and build again.`,
				);
				process.exit(1);
			}
			baseBuildInfo = new BuildInfo(path.join(this.currentDirectory, "flamework.build"));
		} else if (Cache.isInitialCompile) {
			this.buildInfoReused = true;
		}
		this.buildInfo = baseBuildInfo;

		const candidates = Cache.buildInfoCandidates ?? [];
		if (!Cache.buildInfoCandidates) {
			Cache.buildInfoCandidates = candidates;
			const candidatesSet = new Set<string>();
			for (const file of this.program.getSourceFiles()) {
				const buildCandidate = BuildInfo.findCandidateUpper(path.dirname(file.fileName));
				if (
					buildCandidate &&
					!arePathsEqual(buildCandidate, baseBuildInfo.buildInfoPath) &&
					!candidatesSet.has(buildCandidate)
				) {
					candidatesSet.add(buildCandidate);
					candidates.push(buildCandidate);
				}
			}
		}

		for (const candidate of candidates) {
			const relativeCandidate = path.relative(this.currentDirectory, candidate);
			const buildInfo = BuildInfo.fromPath(candidate);
			if (buildInfo) {
				Logger.infoIfVerbose(`Loaded buildInfo at ${relativeCandidate}, next id: ${buildInfo.getLatestId()}`);
				baseBuildInfo.addBuildInfo(buildInfo);
			} else {
				Logger.warn(`Build info not valid at ${relativeCandidate}`);
			}
		}
	}

	private setupRojo() {
		this.pathTranslator = createPathTranslator(this.program);

		const rojoArgvIndex = process.argv.findIndex((v) => v === "--rojo");
		const rojoArg = rojoArgvIndex !== -1 ? process.argv[rojoArgvIndex + 1] : undefined;

		let rojoConfig: string | undefined;
		if (rojoArg && rojoArg !== "") {
			rojoConfig = path.resolve(rojoArg);
		} else {
			rojoConfig = RojoResolver.findRojoConfigFilePath(this.currentDirectory).path;
		}

		if (rojoConfig !== undefined) {
			const rojoContents = fs.readFileSync(rojoConfig, { encoding: "ascii" });
			const sum = crypto.createHash("md5").update(rojoContents).digest("hex");

			if (sum === Cache.rojoSum) {
				this.rojoResolver = Cache.rojoResolver;
			} else {
				this.rojoResolver = RojoResolver.fromPath(rojoConfig);
				Cache.rojoSum = sum;
				Cache.rojoResolver = this.rojoResolver;
			}
		}
	}

	private getIncludePath() {
		const includeArgvIndex = process.argv.findIndex((v) => v === "--i" || v === "--includePath");
		const includePath = includeArgvIndex !== -1 ? process.argv[includeArgvIndex + 1] : undefined;
		return path.resolve(includePath || path.join(this.rootDirectory, "include"));
	}

	/**
	 * Since npm modules can be symlinked, TypeScript can resolve them to their real path (outside of the project directory.)
	 *
	 * This function attempts to convert the real path of *npm modules* back to their path inside the project directory.
	 * This is required to have RojoResolver be able to resolve files.
	 */
	private toModulePath(filePath: string) {
		// The module is under our root directory, so it's probably not symlinked.
		if (isPathDescendantOf(filePath, this.rootDirectory)) {
			return filePath;
		}

		const packageJsonPath = ts.findPackageJson(filePath, ts.sys as never);
		if (!packageJsonPath) {
			throw new Error(`Unable to convert '${filePath}' to module.`);
		}

		const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, { encoding: "utf8" }));
		return path.join(
			this.rootDirectory,
			"node_modules",
			packageJson.name,
			path.relative(path.dirname(packageJsonPath), filePath),
		);
	}

	private calculateGlobs(globs: Record<string, string[]> | undefined) {
		if (!globs) {
			return;
		}

		for (const pathGlob in globs) {
			const paths = glob.sync(pathGlob, {
				root: this.rootDirectory,
				cwd: this.rootDirectory,
				nocase: true,
			});

			globs[pathGlob] = paths.map((globPath) => {
				const outputPath = this.pathTranslator.getOutputPath(globPath);
				return path.relative(this.rootDirectory, outputPath).replace(/\\/g, "/");
			});
		}
	}

	/**
	 * Warns at every use of a glob that matched nothing in this build. Such a glob still resolves, to
	 * no paths, so what it is given to registers or finds nothing; a folder may be empty on purpose,
	 * so this never fails the build.
	 *
	 * It is judged here, once the globs are matched, on every build and on every rebuild of a
	 * watcher, rather than when the file using the glob is transformed: a folder that gains a file
	 * or loses its last one changes the answer without that file being compiled again.
	 */
	private warnEmptyGlobs() {
		const globs = this.buildInfo.getMetadata("globs");
		if (!globs?.paths || !globs.uses) {
			return;
		}

		const paths = globs.paths;

		for (const [origin, uses] of Object.entries(globs.uses)) {
			// A file deleted under a watcher is never compiled again, so its entry outlives it.
			if (!fs.existsSync(path.join(this.rootDirectory, origin))) {
				continue;
			}

			for (const use of uses) {
				if (paths[use.glob]?.length !== 0) {
					continue;
				}

				const glob = use.text === use.glob ? `'${use.glob}'` : `'${use.text}' (${use.glob})`;
				Logger.warn(
					`${origin}:${use.line}:${use.column} - the glob ${glob} given to ${use.macro} matches no files, so nothing is registered or found through it`,
				);
			}
		}
	}

	/**
	 * Warns at every use of a path macro whose Rojo path the place will not have, or will have with no
	 * module under it: judged from what Rojo builds the place from (see `findPlaceSource`), the sources
	 * for a folder inside `out`, and the disk for a `$path` of the project's own. A path that names
	 * nothing compiles all the same, and `registerProviders`, `ComponentPlugin.fromPath` or a macro of
	 * the game's own waits for it at runtime, while `requireModules` raises after five seconds. A
	 * folder with no module is copied into the place empty and registers nothing, and is not in a
	 * clone at all, since git keeps no empty folder. Names below the `$path` are matched exactly: Rojo
	 * names every instance as the file or folder is named on disk, so a path that differs only in case
	 * there finds nothing in the place, whatever the file system allows. A warning, like the empty
	 * glob's, since the build cannot know what the place will hold.
	 *
	 * Judged here, once the build is done, for the reason `warnEmptyGlobs` gives.
	 */
	private warnEmptyPaths() {
		const uses = this.buildInfo.getMetadata("paths")?.uses;
		if (!uses) {
			return;
		}

		// Source paths are resolved against the working directory, as the path translator resolves them.
		const base = process.cwd();
		const states = new Map<string, SourcePathState>();
		const lookUp = (sourcePath: string): SourcePathState => {
			// Judged where the place gets the path from: the deepest `$path` of the Rojo project that
			// covers the Rojo path it compiled to, which may be a folder mapped by a `$path` of its own.
			const rbxPath = this.rojoResolver?.getRbxPathFromFilePath(this.pathTranslator.getOutputPath(sourcePath));
			const inPlace =
				rbxPath !== undefined && this.rojoResolver !== undefined
					? findPlaceSource(
							rbxPath,
							this.rojoResolver.getPartitions(),
							{ rootDir: this.pathTranslator.rootDir, outDir: this.pathTranslator.outDir },
							base,
						)
					: undefined;
			return inPlace ?? findSourcePath(base, sourcePath);
		};

		for (const [origin, fileUses] of Object.entries(uses)) {
			// A file deleted under a watcher is never compiled again, so its entry outlives it.
			if (!fs.existsSync(path.join(this.rootDirectory, origin))) {
				continue;
			}

			// In the order they are written: a chain of calls is transformed from its last call.
			const ordered = [...fileUses].sort((a, b) => a.line - b.line || a.column - b.column);
			for (const use of ordered) {
				let state = states.get(use.path);
				if (state === undefined) {
					state = lookUp(use.path);
					states.set(use.path, state);
				}

				// `requireModules` raises once it has waited five seconds; everything else waits on.
				const call = `${origin}:${use.line}:${use.column} - ${use.macro}("${use.path}")`;
				if (state.kind === "empty") {
					Logger.warn(
						`${call}: nothing in that folder compiles to a module, so the call finds nothing there, and in a place without the folder (git keeps no empty folder) ${use.raises ? "it raises at runtime after waiting five seconds for it" : "it waits for it at runtime"}`,
					);
				} else if (state.kind === "missing") {
					Logger.warn(
						state.actual === undefined
							? `${call}: there is no such file or folder, so the place will not have it, and ${use.raises ? "the call raises at runtime after waiting five seconds for it" : "the call waits for it at runtime"}`
							: `${call}: there is no such file or folder; on disk it is '${state.actual}', and the place names it as the disk does, so ${use.raises ? "the call raises at runtime after waiting five seconds for a name the place does not have" : "the call waits at runtime for a name the place does not have"}`,
					);
				}
			}
		}
	}

	private convertGlobs(
		globs: Record<string, string[]> | undefined,
		luaOut: Map<string, Array<ReadonlyArray<string>>>,
		pkg?: string,
	) {
		if (!globs) {
			return;
		}

		const pkgInfo = pkg ? this.buildInfo.getBuildInfoFromPrefix(pkg) : undefined;
		const root = pkgInfo ? path.dirname(this.toModulePath(pkgInfo.buildInfoPath)) : this.rootDirectory;

		for (const pathGlob in globs) {
			const paths = globs[pathGlob];
			const rbxPaths = new Array<RbxPath>();
			for (const globPath of paths) {
				const rbxPath = this.rojoResolver?.getRbxPathFromFilePath(path.join(root, globPath));
				if (rbxPath) {
					rbxPaths.push(rbxPath);
				}
			}

			luaOut.set(pkgInfo ? pathGlob : this.obfuscateText(pathGlob, "addPaths"), rbxPaths);
		}
	}

	/** The effective transformer options: the `transformer` section of `flamework.config.json`. */
	public config: TransformerConfig;

	/** The `flamework.config.json` the options were read from, if one was found. */
	public configPath?: string;

	/** The whole `flamework.config.json`, including the sections meant for the runtime packages. */
	public projectConfig: ProjectConfig;

	/** The environment the config was substituted from, as read when this process started. `Flamework.env` reads it. */
	public env: Env;

	constructor(
		public program: ts.Program,
		public context: ts.TransformationContext,
		entry: TransformerEntry,
	) {
		const { result: packageJson, directory } = getPackageJson(this.currentDirectory);
		this.rootDirectory = directory;
		assert(packageJson.name);

		// Before the config is read, so the watcher's first read already sees the line and a later
		// read finds nothing changed. A game only: a scoped package is built as a package, by
		// roblox-ts and by Flamework alike, and its own config file is left as its author wrote it.
		const schemaReference = addSchemaReference(this.currentDirectory, this.rootDirectory, entry, {
			isGame: !packageJson.name.startsWith("@"),
		});
		if (schemaReference !== undefined) {
			const file = path.relative(this.currentDirectory, schemaReference.configPath) || schemaReference.configPath;
			Logger.info(
				schemaReference.change === "created"
					? `Created ${file} with a "$schema" line, so editors list every option`
					: `Added a "$schema" line to ${file}, so editors list every option`,
			);
		}

		// Read once per process: a watcher keeps the config and environment it started with, since
		// only the files that changed are recompiled and the rest would disagree with them. Every
		// later compilation reads again only to notice a change and ask for a restart.
		const loaded = loadProjectConfig(this.currentDirectory, this.rootDirectory, entry);
		const fingerprint = fingerprintProjectConfig(loaded);
		if (Cache.projectConfig === undefined) {
			Cache.projectConfig = loaded;
			Cache.projectConfigFingerprint = fingerprint;
		} else if (Cache.projectConfigFingerprint !== fingerprint) {
			Logger.warn(
				"flamework.config.json or .env changed since the watcher started",
				"The values it started with are still in use; restart the watcher to apply the change.",
			);
		}

		const effective = Cache.projectConfig;
		this.config = { ...effective.config };
		this.configPath = effective.configPath;
		this.projectConfig = effective.project;
		this.env = effective.env;

		this.setupRojo();
		this.setupBuildInfo();

		this.config.idGenerationMode ??= this.config.obfuscation ? "obfuscated" : "full";

		const previousMode = this.buildInfo.setIdGenerationMode(this.config.idGenerationMode);
		if (previousMode !== undefined) {
			Logger.info(
				`idGenerationMode changed from '${previousMode}' to '${this.config.idGenerationMode}'; every identifier is regenerated`,
			);
		}

		// Obfuscation is only worth something if a release's ids differ from the last release's.
		// A plain build recreates flamework.build, and with it the salt and the build seed, so
		// that holds on its own; these are the two ways of undoing it.
		if (this.config.obfuscation && Cache.isInitialCompile) {
			if (this.config.salt !== undefined) {
				Logger.warn(
					"transformer.salt is set with obfuscation on",
					"A fixed salt gives every build the same obfuscated ids; leave it unset so each build gets fresh ones.",
				);
			}

			if (this.buildInfoReused) {
				Logger.warn(
					"obfuscated ids were kept from the previous build",
					"This is an incremental build, so files that do not recompile keep their ids and the rest have to match.",
					`Delete ${buildInfoFileName(this.currentDirectory, this.options)} before a release build to rotate every id.`,
				);
			}
		}

		this.packageName = packageJson.name;
		this.isGame = !this.packageName.startsWith("@");
		this.includeDirectory = this.getIncludePath();

		if (!this.isGame) this.config.hashPrefix ??= this.packageName;
		this.buildInfo.setIdentifierPrefix(this.config.hashPrefix);

		if (this.config.hashPrefix?.startsWith("$") && !this.packageName.startsWith(FLAMEWORK_SCOPE)) {
			throw new Error(`The hashPrefix $ is used internally by Flamework`);
		}

		Cache.isInitialCompile = false;

		this.pluginHost = createPluginHost(this);
	}

	getFileId(file: ts.SourceFile) {
		return path.relative(this.rootDirectory, file.fileName).replace(/\\/g, "/");
	}

	saveArtifacts() {
		const start = new Date().getTime();

		this.calculateGlobs(this.buildInfo.getMetadata("globs")?.paths);

		if (this.isGame) {
			const writtenFiles = new Map<string, string>();
			const files = ["globs.json", "config.json", "paths.json"];

			// The runtime sections of flamework.config.json, for the packages to read at runtime.
			const runtimeConfig = getRuntimeConfig(this.projectConfig);
			if (runtimeConfig) {
				// `testing.entry` is a source path in the file; the runner's cloud module needs the
				// ModuleScript, so it is written as a tree path, resolved the way a path macro is.
				const entry = runtimeConfig.testing?.entry;
				if (entry !== undefined) {
					const sourcePath = entry.endsWith(".ts") ? entry : `${entry}.ts`;
					const outputPath = this.pathTranslator.getOutputPath(sourcePath);
					const rbxPath = this.rojoResolver?.getRbxPathFromFilePath(outputPath);
					if (rbxPath === undefined) {
						throw new Error(
							`flamework.config.json: testing.entry '${entry}' is not in the Rojo tree; give the source path of the ModuleScript that exports ignite(), for example "src/server/main"`,
						);
					}
					runtimeConfig.testing = { ...runtimeConfig.testing, entry: rbxPath as unknown as string };
				}
				writtenFiles.set("config.json", JSON.stringify(runtimeConfig));
			}

			// Paths are emitted relative to the Rojo tree's root, which is `game` in a place but the
			// model's own root in a plugin. The runtime finds that root by climbing from the include
			// folder, so this records how far below the root the include folder sits.
			const includeRbxPath = this.rojoResolver?.getRbxPathFromFilePath(this.includeDirectory);
			if (includeRbxPath !== undefined) {
				writtenFiles.set("paths.json", JSON.stringify({ includeDepth: includeRbxPath.length }));
			}

			const packageGlobs = this.buildInfo.getChildrenMetadata("globs");
			const globs = this.buildInfo.getMetadata("globs");
			if (globs || packageGlobs.size > 0) {
				const transformedGlobs = new Map<string, string[][]>();
				this.convertGlobs(globs?.paths, transformedGlobs);

				const transformedPackageGlobs = new Map<string, Record<string, string[][]>>();
				for (const [pkg, packageGlob] of packageGlobs) {
					const transformedGlobs = new Map<string, string[][]>();
					this.convertGlobs(packageGlob?.paths, transformedGlobs, pkg);
					transformedPackageGlobs.set(pkg, Object.fromEntries(transformedGlobs));
				}

				writtenFiles.set(
					"globs.json",
					JSON.stringify({
						game: Object.fromEntries(transformedGlobs),
						packages: Object.fromEntries(transformedPackageGlobs),
					}),
				);
			}

			const metadataPath = path.join(this.includeDirectory, "flamework");
			const metadataExists = fs.existsSync(metadataPath);

			if (!metadataExists && writtenFiles.size > 0) {
				fs.mkdirSync(metadataPath);
			}

			for (const file of files) {
				const filePath = path.join(metadataPath, file);
				const contents = writtenFiles.get(file);
				if (contents) {
					fs.writeFileSync(filePath, contents);
				} else if (fs.existsSync(filePath)) {
					fs.rmSync(filePath);
				}
			}

			if (metadataExists && writtenFiles.size === 0) {
				fs.rmdirSync(metadataPath);
			}
		}

		this.buildInfo.save();

		if (Logger.verbose) {
			// Watch mode includes an extra newline when compilation finishes,
			// so we remove that newline before Flamework's message.
			const watch = process.argv.includes("-w") || process.argv.includes("--watch");
			if (watch) {
				process.stdout.write("\x1b[A\x1b[K");
			}

			Logger.info(`Flamework artifacts finished in ${new Date().getTime() - start}ms`);

			if (watch) {
				process.stdout.write("\n");
			}
		}

		// Printed last: the verbose message above clears the line it takes to be the watcher's blank
		// one, which would be the last warning if the warnings came first.
		this.warnEmptyGlobs();
		this.warnEmptyPaths();
	}

	isUserMacro(symbol: ts.Symbol) {
		const cached = this.isUserMacroCache.get(symbol);
		if (cached !== undefined) return cached;

		if (symbol.declarations) {
			for (const declaration of symbol.declarations) {
				const metadata = NodeMetadata.fromCache(this, declaration);
				if (metadata.isRequested("macro")) {
					this.isUserMacroCache.set(symbol, true);
					return true;
				}
			}
		}

		this.isUserMacroCache.set(symbol, false);
		return false;
	}

	public fileImports = new Map<string, ImportInfo[]>();
	addFileImport(file: ts.SourceFile, importPath: string, name: string): ts.Identifier {
		// Flamework itself uses features which require imports, this will rewrite those imports to be valid inside the Flamework package.
		if (importPath === CORE_PACKAGE && this.packageName === CORE_PACKAGE && name === "Reflect") {
			const modulePath = path.join(this.rootDirectory, "src", "reflect");
			importPath = "./" + path.relative(path.dirname(file.fileName), modulePath) || ".";
		}

		let importInfos = this.fileImports.get(file.fileName);
		if (!importInfos) this.fileImports.set(file.fileName, (importInfos = []));

		let importInfo = importInfos.find((x) => x.path === importPath);
		if (!importInfo) importInfos.push((importInfo = { path: importPath, entries: [] }));

		let identifier = importInfo.entries.find((x) => x.name === name)?.identifier;

		if (!identifier) {
			start: for (const statement of file.statements) {
				if (!f.is.importDeclaration(statement)) break;
				if (!f.is.string(statement.moduleSpecifier)) continue;
				if (!f.is.importClauseDeclaration(statement.importClause)) continue;
				if (!f.is.namedImports(statement.importClause.namedBindings)) continue;
				if (statement.importClause.isTypeOnly) continue;
				if (statement.moduleSpecifier.text !== importPath) continue;

				for (const importElement of statement.importClause.namedBindings.elements) {
					if (importElement.isTypeOnly) {
						continue;
					}

					if (importElement.propertyName) {
						if (importElement.propertyName.text === name) {
							identifier = importElement.name;
							break start;
						}
					} else {
						if (importElement.name.text === name) {
							identifier = importElement.name;
							break start;
						}
					}
				}
			}
		}

		if (!identifier) {
			importInfo.entries.push({ name, identifier: (identifier = f.identifier(name, true)) });
		}

		return identifier;
	}

	getSourceFile(node: ts.Node) {
		const parseNode = ts.getParseTreeNode(node);
		if (!parseNode) throw new Error(`Could not find parse tree node`);

		return ts.getSourceFileOfNode(parseNode);
	}

	getSymbol(node: ts.Node, followAlias = true): ts.Symbol | undefined {
		if (f.is.namedDeclaration(node)) {
			return this.getSymbol(node.name);
		}

		const symbol = this.typeChecker.getSymbolAtLocation(node);

		if (symbol && followAlias) {
			return ts.skipAlias(symbol, this.typeChecker);
		} else {
			return symbol;
		}
	}

	hash(id: number, noPrefix?: boolean) {
		const hashPrefix = this.config.hashPrefix;
		const salt = this.config.salt ?? this.buildInfo.getSalt();
		const hashGenerator = new Hashids(salt, 2);
		if ((this.isGame && !hashPrefix) || noPrefix) {
			return `${hashGenerator.encode(id)}`;
		} else {
			// If the package name is namespaced, then it can be used in
			// other projects so we want to add a prefix to the Id to prevent
			// collisions with other packages or the game.
			return `${hashPrefix ?? this.packageName}:${hashGenerator.encode(id)}`;
		}
	}

	obfuscateText(text: string, context?: string) {
		return this.config.obfuscation ? this.buildInfo.hashString(text, context) : text;
	}

	obfuscateArray<T>(array: ReadonlyArray<T>) {
		return this.config.obfuscation ? shuffle(array) : array;
	}

	addDiagnostic(diag: ts.DiagnosticWithLocation) {
		this.context.addDiagnostic(diag);
	}

	private prereqStack = new Array<Array<ts.Statement>>();
	capture<T>(cb: () => T): [T, ts.Statement[]] {
		this.prereqStack.push([]);
		const result = cb();
		return [result, this.prereqStack.pop()!];
	}

	prereq(statement: ts.Statement) {
		const stack = this.prereqStack[this.prereqStack.length - 1];
		if (stack) stack.push(statement);
	}

	prereqList(statements: ts.Statement[]) {
		const stack = this.prereqStack[this.prereqStack.length - 1];
		if (stack) stack.push(...statements);
	}

	isCapturing(threshold = 1) {
		return this.prereqStack.length > threshold;
	}

	transform<T extends ts.Node>(node: T): T {
		return ts.visitEachChild(node, (newNode) => transformNode(this, newNode), this.context);
	}

	transformNode<T extends ts.Node>(node: T): T {
		// Technically this isn't guaranteed to return `T`, and TypeScript 5.0+ updated the signature to disallow this,
		// but we don't care so we'll just cast it.
		return ts.visitNode(node, (newNode) => transformNode(this, newNode)) as T;
	}

	/**
	 * Returns the identifier to reach `t` from, for generated guards.
	 *
	 * Generated guards use functions such as `t.unionList` that older `@rbxts/t` releases lack. When
	 * the project resolves a different `@rbxts/t` than `@flamework-experimental/core` does, `t` is imported through
	 * core's prelude so that the guards run against the version core was built with.
	 */
	getGuardLibrary(file: ts.SourceFile) {
		if (this.flameworkGuardLibraryPath) {
			return this.addFileImport(file, this.flameworkGuardLibraryPath, "t");
		}

		// Inside the Flamework packages themselves there is nothing to reconcile.
		if (this.packageName.startsWith(`${FLAMEWORK_SCOPE}/`)) {
			this.flameworkGuardLibraryPath = "@rbxts/t";
			return this.addFileImport(file, "@rbxts/t", "t");
		}

		const corePath = tryResolveTS(this, CORE_PACKAGE, file.fileName);
		if (corePath === undefined) {
			Diagnostics.warning(file.endOfFileToken, "Flamework core was not found, guard generation may not work.");
			return this.addFileImport(file, "@rbxts/t", "t");
		}

		const fileGuardPath = tryResolveTS(this, "@rbxts/t", file.fileName);
		const coreGuardPath = tryResolveTS(this, "@rbxts/t", corePath);
		if (fileGuardPath === coreGuardPath) {
			// @flamework-experimental/core and the consuming project are using the same @rbxts/t version.
			this.flameworkGuardLibraryPath = "@rbxts/t";
			return this.addFileImport(file, "@rbxts/t", "t");
		}

		if (
			coreGuardPath === undefined ||
			!isPathDescendantOf(coreGuardPath, path.join(path.dirname(corePath), "../node_modules/@rbxts/t"))
		) {
			Diagnostics.warning(file.endOfFileToken, "Valid `@rbxts/t` was not found, guard generation may not work.");
			return this.addFileImport(file, "@rbxts/t", "t");
		}

		this.flameworkGuardLibraryPath = `${CORE_PACKAGE}/out/prelude`;
		return this.addFileImport(file, this.flameworkGuardLibraryPath, "t");
	}
}

interface ImportItem {
	name: string;
	identifier: ts.Identifier;
}

interface ImportInfo {
	path: string;
	entries: Array<ImportItem>;
}
